# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 371a02bd1f299b7c813ca5c44573ea3dfae55885e9f44425cf935c15a3cb29e6a47eac6d1f436532e07ed1ff15539afc7ba2341b45327fb62c95072dc29d1221

test:
  secret_key_base: 76a42ffb19cdd786857df5ad7eddf65ba9c897e32084d36ef38323a97f2cd2f362c11d8a3ea32bdcaadc19fcfb132b0907310f0faa8f7c9285dfa437be17e5ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
